      - name: Run bot
        env:
          OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
          OKX_API_SECRET: ${{ secrets.OKX_API_SECRET }}
          OKX_API_PASSPHRASE: ${{ secrets.OKX_API_PASSPHRASE }}
          SYMBOL: "BTC/USDT"
          TIMEFRAME: "5m"
          SHORT_SMA: "9"
          LONG_SMA: "21"
          QUOTE_SIZE: "10"
          TESTNET: "true"   # paper trading on OKX when true
        run: python bot.py
